version: '3.4'
services:
  rails: &rails
    build:
      context: .
      dockerfile: ./docker/Rails.dockerfile
    image: hitobito-dev/rails
    depends_on:
    - db
    - mailcatcher
    - cache
    env_file: docker/rails.env
    ports:
    - "3000:3000"
    tmpfs: /opt/app-root/src/hitobito/tmp/pids
    volumes:
    - ./app/:/opt/app-root/src/
    - bundle:/opt/bundle

  worker:
    <<: *rails
    command: [ 'rails', 'jobs:work' ]
    ports: []
    environment:
      SKIP_RAILS_MIGRATIONS: 1
    depends_on:
    - rails
    - db
    - mailcatcher
    - cache

  rails-test:
    image: hitobito-dev/rails-test
    build:
      context: .
      dockerfile: ./docker/Rails-test.dockerfile
    depends_on:
    - rails
    - db
    env_file: ./docker/rails.env
    environment:
      RAILS_ENV: test
      RAILS_DB_NAME: hitobito_test
      RAILS_DB_HOST: db
    volumes:
    - ./app/:/opt/app-root/src/
    - bundle:/opt/bundle

  # Dependencies
  mailcatcher:
    image: hitobito-dev/mailcatcher
    build:
      context: .
      dockerfile: ./docker/Mailcatcher.dockerfile
    ports:
    - "1080:1080"

  cache:
    image: memcached:1.5-alpine
    command: [ memcached, -l, '0.0.0.0', -p, '11211' ]

  sphinx:
    image: macbre/sphinxsearch:3.1.1
    depends_on:
    - db
    volumes:
    - sphinx:/opt/sphinx/index
    - ./docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro

  indexer:
    image: macbre/sphinxsearch:3.1.1
    command: [ indexer, --config, /opt/sphinx/conf/sphinx.conf, --all ]
    depends_on:
    - db
    volumes:
    - sphinx:/opt/sphinx/index
    - ./docker/sphinx.conf:/opt/sphinx/conf/sphinx.conf:ro

  db:
    image: mysql:5.7
    command:
    - --sort_buffer_size=2M
    env_file: ./docker/mysql.env
    ports:
    - "33066:3306"
    volumes:
    - ./docker/mysql-setup.sql:/docker-entrypoint-initdb.d/mysql-setup.sql:ro
    - db:/var/lib/mysql

volumes:
  db:
  sphinx:
  bundle:
